### ISSUE TITLE
Add HCL extensions to Samplr allowlist

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/devrel-services#140]
Samplr should start returning snippets for these extensions:

```
HCL:
  type: programming
  extensions:
  - ".hcl"
  - ".nomad"
  - ".tf"
  - ".tfvars"
  - ".workflow"
  aliases:
  - HashiCorp Configuration Language
  - terraform
  ace_mode: ruby
  codemirror_mode: ruby
  codemirror_mime_type: text/x-ruby
  tm_scope: source.terraform
  language_id: 144
```
